### ISSUE TITLE
switch on schedstat support via sysctl on newer kernel

### ISSUE THREAD

**Issue by mbiebl** [systemd/systemd-bootchart#12]
As of kernel 4.6, there is now a run-time switch for schedstats support, which defaults to disabled.
It can be switched on via a kernel command line parameter or  sysctl  [1]

Please update systemd-bootchart to automatically flip that runtime switch via sysctl so fiddling with the kernel command line is not necessary.

[1] https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=cb2517653fccaf9f9b4ae968c7ee005c1bbacd

**Comment by sofar** [comment]
Good catch.

I think we can just write `1` to `/proc/sys/kernel/sched_schedstats` and ignore any errors. If the file is missing it's likely an older kernel, or the feature is disabled.

We may just want to leave a note in the bootchart.svg that schedstats are possibly disabled.

**Comment by mbiebl** [comment]
Yep, works nicely now (on Debian unstable with kernel 4.7.0-1-amd64)

**Comment by sofar** [comment]
Awesome, thanks for confirming.
