### ISSUE TITLE
If `/proc` is not mounted, `systemd-bootchart` exits immediately instead of waiting

### ISSUE THREAD

**Issue by codyps** [systemd/systemd-bootchart#22]
Especially noticeable in the `init=.../systemd-bootchart` case where `/proc` is not mounted early enough unless some special setup (a pre-init prior to systemd-bootchart that mounts `/proc`) is done.

Note that the comment on https://github.com/systemd/systemd-bootchart/blob/69533674288ca69a64ed5ae5dc91c0707619edab/src/bootchart.c#L424-L429 is incorrect, if `/proc` is not mounted `log_sample` returns the `-errno` of the failed `openat()` call on `/proc/vmstat`, causing the program to exit immediately.

This regression appears to have been introduced back in [commit f91781329c6d8a760e3c1b88b66b0e2137c2e5ab of systemd](https://github.com/systemd/systemd/commit/f91781329c6d8a760e3c1b88b66b0e2137c2e5ab) (prior to the split between this and that repo).

As a workaround, one can pre-mount `/proc`.

**Comment by sofar** [comment]
I was suspecting this. The original version that merged with systemd mounted `/proc` itself manually to avoid any such issues. I'm wondering if we should just put that back, since any other solution is problematic, and there is little harm in mounting proc again at the same mount point (it's just a no op as far as I know).

**Comment by questor** [comment]
short ping, I have the same issue. fix would be nice, bootchart is complaining that it can't open /proc/vmstat

**Comment by sofar** [comment]
yeah, I just did some archaeology and I can't find any code base that mounted `/proc` to begin with.

The bug introduced by https://github.com/systemd/systemd/commit/f91781329c6d8a760e3c1b88b66b0e2137c2e5ab is indeed changing the code to unwanted behavior, so we'll need to at least undo that.

But I'm skeptical about mounting `/proc` as a good solution.

**Comment by sofar** [comment]
395d046
