### ISSUE TITLE
Bootchart leaks file handles. Get "Too many open files" on boots that launch many processes

### ISSUE THREAD

**Issue by cmtm** [systemd/systemd-bootchart#25]
The bootchart process leaks file handles to `/proc/PID/schedstat`, `/proc/PID/shed`, and to `/proc/PID/smaps` (when arg_pss is set). It seems that this is known, as bootchart increases it's maximum file descriptor count to 4096. Unfortunately, this strategy fails when we have a boot with lots of launched processes.

### How the leak happens

At every sample, bootchart loops through the entries in `/proc` (ignoring those that aren't numbers), and traverses it's linked list of known processes. If the process is a new one, it allocates a new `ps_struct`. When it allocates this structure, it opens the file `/proc/PID/sched` and sets `ps_struct->sched` to that file descriptor. If the process is one that's already known, it just uses the existing `ps_struct` in the linked list; no new files are opened.

It only ever closes the file if it fails to read from it in a sample. If the process dies any time between when it find's the entry in `/proc` and when it gets to reading the file, bootchart won't close the file handle until the end of the boot. For sample periods that aren't taxing the CPU, this means that most of the file handles won't be closed.

### Possible solutions

The trivial solution would be to open and close the file descriptor on every sample. I'm not sure how this would affect performance though, as I suspect the reason it wasn't already done this way was to minimize bootchart's overhead.

I've thought of an alternate solution that would keep a separate list of "active processes", and look through them when looping over the entries of `/proc/`. It would then be easy keep track of which processes need to have their file handles closed. I think this would have the added benefit that it could improve overall performance, since the length of the list of `ps_struct`s that we need to walk through for every entry in `/proc` would be much smaller for many systems. Would you welcome a pull request with this alternate solution?

**Comment by sofar** [comment]
Open/close calls are the major overhead for the process, which is why it keeps all of them open. If we can do a better job pruning fds then I'll gladly take it.

**Comment by cmtm** [comment]
I ran bootchart under valgrind to profile it, and I noticed that the relative time spent in the open and close calls was small (less than 1%) both in bootchart's current state and with a modification which opens and closes the files on every iteration. In both cases, the sscanf, snprintf, linked list traversal, and (surprisingly) hidden_file functions dominated the overhead.

I understand than these numbers would be very system specific, so I was wondering if there was a kind of reference system (CPU, number of processes started during boot, ...) that you used to determine where most of the overhead was? I want to make sure that whatever changes I propose wouldn't increase the overhead for that system.

**Comment by sofar** [comment]
>I understand than these numbers would be very system specific, so I was
>wondering if there was a kind of reference system (CPU, number of
>processes started during boot, ...) that you used to determine where
>most of the overhead was? I want to make sure that whatever changes I
>propose wouldn't increase the overhead for that system.

This optimization comes all the way back from the Meego/moblin 2 days, so we're talking first gen atom (1.1ghz, very slow storage). I don't think CPU time was an issue, just syscalls in general.

**Comment by sofar** [comment]
Is this something we can close? @cmtm?

**Comment by cmtm** [comment]
Yep, fixed by #27
