### ISSUE TITLE
Timestamp numbers on graphs overlap making them unreadable.

### ISSUE THREAD

**Issue by cmtm** [systemd/systemd-bootchart#26]
This is only observed with commit 8b28975438ac06ee54f2151197274afe08762542 (the current HEAD of the branch).

Before:
![good_spacing](https://cloud.githubusercontent.com/assets/3279196/23529297/164bcb34-ff6b-11e6-945b-a1476a10f5f0.PNG)

After:
![bad_spacing](https://cloud.githubusercontent.com/assets/3279196/23529288/12842adc-ff6b-11e6-9a1d-a9d9563d0a86.png)

**Comment by mbiebl** [comment]
I can confirm that. The time labels are unreadable. Reverting 8b28975 fixes this.

/cc @xnox

**Comment by xnox** [comment]
Hm, sad. It didn't used to be like this. @ahkok is bootchart working fine for you?

**Comment by ahkok** [comment]
I've only been looking at default scaling options, so I hadn't seen this.

what `scale_x` is this using? We'll get it fixed up.

edit: got it, nvm.

**Comment by ahkok** [comment]
tbh the default horizontal scaling change doesn't make much sense to me, so I'll likely revert that.

**Comment by sofar** [comment]
84267f9

I tested the full range and this fixes all the readability issues across the entire range, so I think this closes the bugreport.
