### ISSUE TITLE
Version numbering scheme

### ISSUE THREAD

**Issue by sofar** [systemd/systemd-bootchart#8]
I'm proposing to return to X.Y versioning scheme numbering, starting with "3.0".

Rationale:
- Using the current systemd numbering would remain confusing forever. If we use 230 for the next tagged release, it will only give confusion to users. If we use 1000 or some arbitrary higher number, the confusion isn't removed.
- The first-gen codebase was numbered 1.x (1.0 through 1.19 or so), and the in-systemd tree was the second gen. So, logically, the current tree is "3rd gen" hence 3.X numbering would have some logical meaning and would help people to track down the right codebase to fix bugs in.

**Comment by sofar** [comment]
@systemd/bootchart-maintainers please comment or signal approval, so we can start tagging releases.

**Comment by zonque** [comment]
I wouldn't bother too much and stick to the single-level version number, especially for such a small tool as bootchart. You will unlikely need to have stable releases with backported patches, so there's no gain in multiple levels. But those are just my 2¢, I'll leave the decision entirely to you, as you are the main developer of that code :)

**Comment by sofar** [comment]
well the problem I see is with us tagging 230 and people looking in systemd-230 for the code :)

**Comment by zonque** [comment]
So? Let them. The version numbers will divert soon enough, and you cannot avoid two different software projects having similar version numbers. So there's nothing to win or lose here :)

**Comment by sofar** [comment]
Alright, let's just do that then. Thanks for chiming in.

**Comment by sofar** [comment]
Decision: continue from 230.
